### ISSUE TITLE
Crash on crop click when destroy event cancelled (i'm guessing....)

### ISSUE THREAD

**Issue by sudofox** [Tr4nter/auto-plant-crop#15]
```
[17:04:08] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'net.minecraft.class_1799 net.minecraft.class_2302.method_9574(net.minecraft.class_4538, net.minecraft.class_2338, net.minecraft.class_2680)'
	at net.minecraft.class_636.handler$zbg000$auto-plant-crops$attackBlock(class_636.java:646) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2899(class_636.java:138) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41930(class_636.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41931(class_636.java:278) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2910(class_636.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1536(class_310.java:1788) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2099) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1933) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[17:04:08] [Render thread/INFO]: [voicechat] Clearing audio channels
[17:04:08] [Render thread/INFO]: [voicechat] Stopping microphone thread
[17:04:08] [Render thread/INFO]: [voicechat] Disconnecting voicechat
[17:04:08] [Render thread/INFO]: Minimap session finalized.
[17:04:08] [Render thread/INFO]: Finalizing world map session...
```

happens when i click a crop when coreprotect inspector mode is on.

**Comment by sudofox** [comment]
actually, it happened even with it off... not sure what's going on. 1.20.2 latest

**Comment by Tr4nter** [comment]
Wasn't able to reproduce the bug on a server with coreprotect inspector mode on, Could you provide the full crash log?

**Comment by Soupertonic** [comment]
I got a crash too on a fresh install. It is not obvious what the crash caused except that some method is not available.

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-01-10 19:36:26
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.class_1799 net.minecraft.class_2302.method_9574(net.minecraft.class_4538, net.minecraft.class_2338, net.minecraft.class_2680)'
	at net.minecraft.class_636.handler$zza000$auto-plant-crops$attackBlock(class_636.java:646)
	at net.minecraft.class_636.method_2899(class_636.java:138)
	at net.minecraft.class_636.method_41930(class_636.java:181)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2910(class_636.java:175)
	at net.minecraft.class_310.method_1536(class_310.java:1788)
	at net.minecraft.class_310.method_1508(class_310.java:2099)
	at net.minecraft.class_310.method_1574(class_310.java:1933)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_636.handler$zza000$auto-plant-crops$attackBlock(class_636.java:646)
	at net.minecraft.class_636.method_2899(class_636.java:138)
	at net.minecraft.class_636.method_41930(class_636.java:181)
	at net.minecraft.class_636.method_41931(class_636.java:278)
	at net.minecraft.class_636.method_2910(class_636.java:175)
	at net.minecraft.class_310.method_1536(class_310.java:1788)
	at net.minecraft.class_310.method_1508(class_310.java:2099)

-- Affected level --
Details:
	All players: 1 total; [class_746['Soupertonic'/20059, l='ClientLevel', x=648.30, y=60.94, z=7997.58]]
	Chunk stats: 729, 256
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,64,0), Section: (at 0,0,0 in -2,4,0; chunk contains blocks -32,-64,0 to -17,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 43633276 game time, 45081534 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:451)
	at net.minecraft.class_310.method_1587(class_310.java:2481)
	at net.minecraft.class_310.method_1514(class_310.java:880)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 445620192 bytes (424 MiB) / 1115684864 bytes (1064 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600X 6-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2487
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4633
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34742.05
	Virtual memory used (MB): 12764.80
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		auto-plant-crops: Auto Plant Crops 1.1.7
		fabric-api: Fabric API 0.91.3+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.79+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.9+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.3+b8b4f0e5a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.12+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.10+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.11+239dafd8a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.45+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.12+4944b5a5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.2
		xaerominimap: Xaero's Minimap 23.9.3
	JVM uptime in seconds: 39.03
	Launched Version: fabric-loader-0.15.3-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.33, NVIDIA Corporation
	Window size: 2560x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_US
	CPU: 12x AMD Ryzen 5 5600X 6-Core Processor 
```

**Comment by sudofox** [comment]
I just realized, if you grab a copy of the fabric mappings you can figure out what it is

**Comment by Tr4nter** [comment]
I seems to have found the problem and have published a fix, due to there being multiple solutions to this, and the part where I wasn't able to reproduce the crash, It would be kind of you guys to help me test out the fix 
https://github.com/Tr4nter/auto-plant-crop/releases/tag/1.1.8

**Comment by sudofox** [comment]
I'll give it a try in a day or two when I have a sec to play MC

**Comment by Soupertonic** [comment]
I can confirm that works now without any issues. Thank you for fixing it.
