### ISSUE TITLE
Latest version doesn't work with 1.19.4

### ISSUE THREAD

**Issue by ImNotStable** [Tr4nter/auto-plant-crop#6]
This states the latest version supports 1.19.4
![image](https://github.com/Tr4nter/auto-plant-crop/assets/51060503/71f6ea35-537d-44a9-b48f-ceecf484377a)
This is the error message
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Auto Plant Crops' (auto-plant-crops) 1.0.0 with any version that is compatible with:
		 - minecraft 1.19.4
Unmet dependency listing:
	 - Mod 'Auto Plant Crops' (auto-plant-crops) 1.0.0 requires any version between 1.20 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Tr4nter** [comment]
Hello, thanks for reporting the issue, I have updated it to be able to support 1.19+
https://modrinth.com/mod/auto-plant-crops/version/1.0.9c
